version: "2"
services:
  bike:
    container_name: Bike
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
  db:
    container_name: Database
    image: mysql
    volumes:
      - ./tmp:/var/lib/mysql
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: bodygler
