version: "2"
services:
  bike:
    container_name: Bike
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:mssql
  mssql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: "mssql"
    environment:
        - SA_PASSWORD=MyRandomPassword123
        - ACCEPT_EULA=Y